
spring:
  application.name: Server
  datasource:
    url: jdbc:postgresql://localhost:5432/rallymaster
    username: rallymaster
    password: rallyhq
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        generate_statistics: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  access-token:
    expiration: 900000  # 15 minutes
  refresh-token:
    expiration: 2592000000  # 30 days

logging:
  level:
    root: INFO

